// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJf6i7F7juyycmy5F8Z1zM0_MnZeq28ko',
    appId: '1:246955389010:android:a36eb6467ccf7d1cb5ef8b',
    messagingSenderId: '246955389010',
    projectId: 'scanbite-a7d63',
    databaseURL: 'https://scanbite-a7d63-default-rtdb.firebaseio.com',
    storageBucket: 'scanbite-a7d63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDsGMmmN6zwUWn76iwOTnEm1RWDXJVIc',
    appId: '1:246955389010:ios:9a53746100bb41a3b5ef8b',
    messagingSenderId: '246955389010',
    projectId: 'scanbite-a7d63',
    databaseURL: 'https://scanbite-a7d63-default-rtdb.firebaseio.com',
    storageBucket: 'scanbite-a7d63.firebasestorage.app',
    androidClientId: '246955389010-089s0gu5jutq1ah46hnqos2c84js1gom.apps.googleusercontent.com',
    iosClientId: '246955389010-1tpubrvr1en32aeataif867tpi7gs3c1.apps.googleusercontent.com',
    iosBundleId: 'com.an2app.scanbite',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hUvWQGF5HZuSeaWdyU7kXxyG--SB1A4',
    appId: '1:246955389010:web:f898bd90e3e8744eb5ef8b',
    messagingSenderId: '246955389010',
    projectId: 'scanbite-a7d63',
    authDomain: 'scanbite-a7d63.firebaseapp.com',
    databaseURL: 'https://scanbite-a7d63-default-rtdb.firebaseio.com',
    storageBucket: 'scanbite-a7d63.firebasestorage.app',
    measurementId: 'G-2ZFQCWYHTS',
  );
}
